### PR TITLE
Add Reference to Feline Watchdog in NTFY Client Code

### PR DESCRIPTION
**Pull request by Paschalis**
#### Summary

This pull request updates the `README.md` of the `ntfy_on_a_chip` repository to include a reference to the `Feline Watchdog` project. The `Feline Watchdog` project is an ESP32-based system designed to monitor Wi-Fi connectivity for a cat's collar-mounted ESP32 device and send alerts when the connection is lost. This showcases a practical application of the `ntfy_on_a_chip` example code in a real-world scenario.

#### Changes Made

- Added a section in the `README.md` file of `ntfy_on_a_chip` to describe the `Feline Watchdog` project.
- Provided a brief overview of the `Feline Watchdog` project and how it utilizes the `ntfy_on_a_chip` code.
- Added links to the `Feline Watchdog` repository and documentation.

#### Details

The `Feline Watchdog` project demonstrates a practical application of the `ntfy_on_a_chip` example code by integrating it with a system that monitors an ESP32-based device's connection status. The project shows how the NTFY service can be used to send notifications when the device goes out of range, which could be particularly useful for pet owners.

##### Feline Watchdog Overview

- **Purpose**: To alert pet owners when their cat's ESP32 collar-mounted device loses Wi-Fi connection, indicating the cat may be out of range.
- **Components**:
  - ESP32 microcontroller
  - Raspberry Pi (optional) or direct connection to a home router
  - Notification setup using NTFY

##### How It Uses NTFY

The `Feline Watchdog` project uses the `ntfy_on_a_chip` example code to establish communication between the ESP32 and the NTFY server. When the ESP32 detects a loss of connection, it triggers a notification via NTFY to alert the user. This real-world application highlights how the NTFY service can be employed in practical scenarios beyond basic examples.

For more information on the `Feline Watchdog` project, please visit the [Feline Watchdog Repository](https://github.com/k-antoniou/FelineWatchdog).

#### Conclusion

By including this reference, users of `ntfy_on_a_chip` can see a practical use case of the example code and find inspiration for their own projects. This integration demonstrates the versatility of NTFY in various applications, from simple demonstrations to more complex, real-world scenarios.

---

Thank you for considering this addition to the `ntfy_on_a_chip` repository. I believe this will help users understand the broader applications of the example code and encourage further experimentation and innovation.

### CODE REVIEW

**Comment by gergepalfi** [comment]
Seems good at a first glance. Will merge later when I have time to check.

**Comment by gergepalfi** [comment]
I found one issue that needs to be resolved before merging. You are redistributing GPLv3 code under MIT license. This is a problem because MIT allows modifications without redistributing changes as open source (essentially allowing to make it proprietary). If you view the license file, Github displays a summary of points on top to make it clear.

**Comment by gergepalfi** [comment]
- fix license (not MIT, especially not in my readme)
- avoid repetition (top of file)
- DO NOT remove information (20 year certificate lifespan, littleFS link, ESP8266 instructions, 4M flash layout, functionality with piled up messages, library folder to find script...)
- Keep the example project section short (description and a link, the power supply is irrelevant information here)

**Comment by Paschalis** [comment]
Thank you for the detailed feedback. I’ve made the requested updates and hope they address your concerns. Please let me know if any further changes are needed. Looking forward to your feedback.

Thanks again for your support and for maintaining such a useful project!

**Comment by darkman7hr** [comment]
has anybody done such project? I've done several but with BLE only. Smallest was JDY-23 directly soldered to tiny battery. It required a lot of work and firmware changes.. or buying one that would support setting interval, txpow etc.. Now I use ready made "HolyIoT" module with coin battery and works for months (6-9) with interval 7-8 sec and txpow 2 of 5 (cant remember scale) . I have display with cat position inside and outside house. I doubt esp can do that much to top that battery efficiency. Right?

**Comment by gergepalfi** [comment]
@Paschalis Thanks for the corrections and respecting the license terms.

PS: If I could give a suggestions for your project, have a look at [RaspAP](https://raspap.com/) as an option for running on a Pi. I used it for 2 years and I recommend it (as long as you don't have more than 8 cats connected to it because the broadcom wifi on the Pi can only take few connections)

**Pull request merged**
